services:
  db:
    image: postgres:16
    restart: always
    shm_size: 256mb
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=app
    ports:
      - "1234:5432"
    
  cache:
    image: redis:7
    restart: always
    ports:
      - "1235:6379"

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:example@db:5432/app
      - CACHE_URL=redis://cache:6379/0